### PR TITLE
Update integration to support VTK 9.1

### PR DESCRIPTION
**Pull request by jcfr**
In addition of the API changes documented below, this commit also updates
`vtkVirtualRealityViewInteractor` to allow retrieving the last tracked device
position stored in the array `vtkOpenVRRenderWindowInteractor::Trackers`.

The `Trackers` array contains `TrackerActions` each being a struct with
two entries:
- `Source` of type `vr::VRInputValueHandle_t`
- `LastPose` of type `vr::TrackedDevicePose_t`

Obsolete branches
-----------------

| branch | Notes |
|--|--|
| [cpinter@slicervr-vtkrenderingvr-build](https://github.com/cpinter/SlicerVirtualReality/tree/slicervr-vtkrenderingvr-build) | **Remove**, change integrated in this PR (#90) |
| [cpinter@fix-build-against-vtk-9.1.20211022](https://github.com/cpinter/SlicerVirtualReality/tree/fix-build-against-vtk-9.1.20211022) | **Remove**, change integrated in this PR (#90) |
| [cpinter@gui-widgets-module](https://github.com/cpinter/SlicerVirtualReality/tree/gui-widgets-module) | **Remove**, change integrated in this new branch: [jcfr@fix-build-against-vtk-9.1.20211022-with-gui-widgets-module](https://github.com/jcfr/SlicerVirtualReality/compare/fix-build-against-vtk-9.1.20211022...fix-build-against-vtk-9.1.20211022-with-gui-widgets-module) |

Remaining issues
----------------

### (1) Retrieval of last position associated with generic tracker

Retrieval of last position associated with generic tracker in
`vtkVirtualRealityViewInteractor::GetTrackedDevicePose` given
the index is not possible.

**:warning: TODO**: Handle retrieval of tracker position associated with generic tracker associated with index.

Background:

Add support for generic tracker originally contributed in these commits:
* kitware/VTK@6083532cf8 (ENH: Exposing the generic tracker openvr device type to downstream projects)
* KitwareMedical/SlicerVirtualReality@59b7d1bf3 (Adding interface and logic to maintain MRML transforms for each generic VR tracker)

but removed following the refactoring done in these commits:

* kitware/VTK@1aac3fe5f (Create VRInteractorStyle and VRRenderWindowInteractor)
* kitware/VTK@af0fab486 (Clean up VR and OpenVR classes)
* kitware/VTK@9bd64d666 (Cleanup and rework of the VRInteractorStyle and subclasses)
* kitware/VTK@09a478a22 (Cleanup VR camera code and subclasses)

### (2) RecognizeComplexGesture is not virtual  anymore in base VTK class

**:warning: TODO**: Assess with this function should still be overriden with VTK 9.1

Background: The function became non virtual in Kitware/VTK@af0fab486 (Clean up VR and OpenVR classes)

API changes
-----------

vtkEventData API changes:
* vtkEventDataButton3D -> vtkEventDataDevice3D

RenderWindow API changes
* GetNumberOfTrackedDevicesForDevice -> GetNumberOfDeviceHandlesForDevice
* GetTrackedDeviceIndexForDevice -> GetDeviceHandleForDevice
* GetTrackedDeviceModel -> GetModelForDevice
* GetTrackedDeviceIndexForDevice -> GetDeviceHandleForDevice

InteractorStyle API changes
* PositionProp sinature updated to include "lwpos" and "lwori"

### CODE REVIEW

**Comment by cpinter** [comment]
I can confirm that the branch https://github.com/jcfr/SlicerVirtualReality/compare/fix-build-against-vtk-9.1.20211022...fix-build-against-vtk-9.1.20211022-with-gui-widgets-module builds. I'll test it tomorrow in the office where I have access to VR hardware.

**Comment by cpinter** [comment]
I finally could test it with a Slicer build from March 1st. There are a few issues, but it's a bit tricky to know what is because of what.

Scenario 1: HP Reverb 2 on Windows 11 (Windows updated from 10 without asking)
- Virtual reality rendering works, as well as moving objects and two-handed navigation (i.e. pinch 3D)
- Volume rendering does not work, meaning that it shows up in 2D but not in 3D. However (!) it does not work either in my previous build that we used (Jan 31) it successfully before the machine updated to Win11, so it seems to be due to this update.
- Flying does not work

Scenario 2: HTC Vive Pro on Windows 10
- Virtual reality rendering DOES NOT WORK. It shows up for around half a second, then an error message pops up, see below
- On this configuration with the Jan 31 build, virtual reality works
    - Also, flying works, as well as volume rendering

20220304_ViveError

**Comment by cpinter** [comment]
@jcfr I can work a bit on this today. I'll check out the flying issue, and see if there is anything else to fix before integration (volume rendering works, it was simply a driver issue - see [here](https://discourse.slicer.org/t/volume-rendering-on-windows-11/22402)).

Please let me know if I should check out anything specific.

**Comment by jcfr** [comment]
> re: action manifest error 

I suggest you try copying the relevant file in the current working directory.

Looking at https://github.com/Slicer/VTK/blob/slicer-v9.1.20220125-efbe2afc2/Rendering/OpenVR/vtkOpenVRRenderWindowInteractor.cxx#L34, we can see that the filename is looked using `./vtk_openvr_actions.json`

The files are the following:

https://github.com/Slicer/VTK/tree/slicer-v9.1.20220125-efbe2afc2/Rendering/OpenVR 

and can be downloaded from:

image

or copied around from your source tree .


References:
* 
*

**Comment by lassoan** [comment]
@cpinter We are working on fixing all extension builds for Slicer5. There are now only two extensions - SlicerVirtualReality and SlicerRadiomics - that must be fixed before the new release: https://docs.google.com/spreadsheets/d/1GC4DWDpOXhuDYdfYOjJ6PmjHTeMM3-K7SoiC5ZR1GYg/edit?usp=sharing

 It would be great if you could finalize this pull request so that we can start the Slicer5 release process.

**Comment by cpinter** [comment]
This is on my list every single day, but I have a very hard time finding time to work on this these weeks. I still haven't been able to reinstall the computer that I use for VR. Hopefully tomorrow I can do that, but to spend even two hours fixing real issues is quite unlikely over the next two weeks or so.

I'd say that we integrate this to fix the build, and then fix the remaining issues afterwards. I cannot say with certainty that there are actual issues with the extension that haven't been there before, because my VR computer acted up as well as @dgmato 's, and nobody else seems to have tested this. Having the extension build successfully would at least facilitate this.

**Comment by lassoan** [comment]
OK, thanks, I'll merge the changes then.

**Comment by cpinter** [comment]
Great, let's see the dashboard tomorrow, it should be green and I'll at least try to test it with the preview after reinstall.

Sorry I haven't been more help with this, but sometimes projects pile up.

**Comment by jcfr** [comment]
I copied the summary of _remaining issues_ related to the integration with VTK 9.1 in https://github.com/KitwareMedical/SlicerVirtualReality/issues/91

These would still need to be addressed.

**Pull request merged**
