### PR TITLE
Update build system to support building against VTK9

### PR DESCRIPTION
**Pull request by jcfr**
* Update `SuperBuild.cmake` to fetch sources of [VTKExternalModule](https://github.com/KitwareMedical/VTKExternalModule) project.

* Split `VTKRenderingOpenVR` external project to configure and build
  the `OpenVR` sources using `VTKExternalModule` buildsystem.

* Rename `OPENVR_*` variables to `OpenVR_*`.

* Update packaging rules to install "runtime" and "python" components.

* Fix build issues

### CODE REVIEW

**Comment by adamrankin** [comment]
Even with the external module project, a number of files are generated inside the source directory using VS2019. It's not really a problem, just sub-optimal.

**Comment by adamrankin** [comment]
image

**Comment by jcfr** [comment]
>  a number of files are generated inside the source directory using VS2019. It's not really a problem, just sub-optimal.

Thanks for reporting this. This can be observed independently of the generator, I am currently working on a VTK patch to address the issue.

**Comment by jcfr** [comment]
> currently working on a VTK patch to address the issue.

See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8123

I will also backport the change into out Slicer/VTK

**Comment by jcfr** [comment]
> backport the change into our `Slicer/VTK` fork

Here it is: https://github.com/Slicer/Slicer/pull/5714

**Comment by adamrankin** [comment]
Building now, will report back

**Comment by jcfr** [comment]
I identified one issue that I will be fixing shorty.

**Review by cpinter — APPROVED** [review]
I tested the build as well and it seems to work well. I'm not saying I understand how VTKExternalModule works exactly, but it does :) Thank you!

**Review by adamrankin — APPROVED** [review]
Build works for me!

**Pull request merged**
