### PR TITLE
COMP: Attempt to fix build including vtkRenderingVR WIP

### PR DESCRIPTION
**Pull request by cpinter**
@jcfr We're trying yo fix SlicerVR build against this branch: https://github.com/Slicer/Slicer/pull/5978

I included VTK::RenderingVR, which is a new common dependency for vtkRenderingOpenVR and the new vtkRenderingOpenXR, and it builds successfully, but for some reason CMake does not find vtkRenderingVR for vtkRenderingOpenVR. The error message is simply
```
  CMake Error at E:/e/Slicer/CMake/ExternalProjectDependency.cmake:860 (message):
    Can't find External_VTK::RenderingVR.cmake
  Call Stack (most recent call first):
    SuperBuild/External_vtkRenderingOpenVR.cmake:20 (ExternalProject_Include_Dependencies)
    E:/e/Slicer/CMake/ExternalProjectDependency.cmake:844 (include)
    SuperBuild.cmake:49 (ExternalProject_Include_Dependencies)
    CMakeLists.txt:32 (include)
```

I tried to add RenderingVR everywhere it seemed to make any sense (probably too many places actually), but the error is the same.

Any ideas? Thanks a lot!

### CODE REVIEW

**Comment by cpinter** [comment]
@jcfr Even if you have one minute to look at this it would help because probably the solution is trivial. Thank you!

**Comment by cpinter** [comment]
After a bit more trying I get as far as this error

```
   The VTK::RenderingVR dependency is missing for VTK::RenderingOpenVR.
  Call Stack (most recent call first):
    CMakeLists.txt:81 (vtk_module_build)
```

My suspicion is that we cannot simply build two external VTK modules from which one depends on the other. What needs to be defined/added? Thank you!

**Comment by jcfr** [comment]
We need to add External_vtkRenderingVR .cmake external project.

**Comment by cpinter** [comment]
Yes we have it and it builds as well. It's just not found by the second VTK external module. Please see code in this PR.

**Comment by cpinter** [comment]
I quickly talked with @lassoan and together we found out a few things:

* The reason the vtkRenderingOpenVR does not find the vtkRenderingVR is that its targets CMake file is not included
* We manually included the targets CMake file in `SlicerVirtualReality_D\VTKExternalModule\CMakeLists.txt` with a hard-coded local path like this `include("e:/e/_Extensions/SlicerVirtualReality_D/vtkRenderingVR-build/lib/cmake/vtk/vtkRenderingVR-targets.cmake")` and it worked
* So what we'd need to do is to make sure that the `SlicerVirtualReality_D\vtkRenderingOpenVR-build\lib\cmake\vtk\vtkrenderingopenvr-config.cmake` file includes the targets file of its dependencies as well
* To achieve that we need to improve the `VTKExternalModule\CMake\vtkmodule-config.cmake.in` file ([see here](https://github.com/KitwareMedical/VTKExternalModule/blob/main/CMake/vtkmodule-config.cmake.in)) so that it goes through its dependencies and includes the same two CMake files with the correct paths.

@jcfr does this approach seem to make sense? Thanks!

**Comment by jcfr** [comment]
Now that the build-system integration should be addressed, building the extension against https://github.com/Slicer/Slicer/pull/5978 leads to the following error:


```
In file included from /home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:21:
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.h:43:16: error: ‘virtual void vtkVirtualRealityViewInteractor::RecognizeComplexGesture(vtkEventDataDevice3D*)’ marked ‘override’, but does not override
   43 |   virtual void RecognizeComplexGesture(vtkEventDataDevice3D* edata) override;
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:28:
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.h:98:16: warning:   by ‘virtual void vtkVirtualRealityViewInteractorStyle::PositionProp(vtkEventData*)’ [-Woverloaded-virtual]
   98 |   virtual void PositionProp(vtkEventData *);
      |                ^~~~~~~~~~~~
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx: In member function ‘virtual void vtkVirtualRealityViewInteractor::RecognizeComplexGesture(vtkEventDataDevice3D*)’:
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:76:19: error: ‘class vtkVirtualRealityViewInteractor’ has no member named ‘DeviceInputDown’; did you mean ‘DeviceInputDownCount’?
   76 |         if (this->DeviceInputDown[*buttonIt][0] && this->DeviceInputDown[*buttonIt][1])
      |                   ^~~~~~~~~~~~~~~
      |                   DeviceInputDownCount
/home/jcfr/Projects/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:76:58: error: ‘class vtkVirtualRealityViewInteractor’ has no member named ‘DeviceInputDown’; did you mean ‘DeviceInputDownCount’?
   76 |         if (this->DeviceInputDown[*buttonIt][0] && this->DeviceInputDown[*buttonIt][1])
      |                                                          ^~~~~~~~~~~~~~~
      |                                                          DeviceInputDownCount
make[5]: *** [VirtualReality/MRML/CMakeFiles/vtkSlicerVirtualRealityModuleMRML.dir/build.make:138: VirtualReality/MRML/CMakeFiles/vtkSlicerVirtualRealityModuleMRML.dir/vtkVirtualRealityViewInteractor.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1112: VirtualReality/MRML/CMakeFiles/vtkSlicerVirtualRealityModuleMRML.dir/all] Error 2
make[3]: *** [Makefile:166: all] Error 2
make[2]: *** [CMakeFiles/inner.dir/build.make:87: inner-prefix/src/inner-stamp/inner-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:924: CMakeFiles/inner.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

```

**Comment by jcfr** [comment]
I will integrate changes from this branch:
* https://github.com/cpinter/SlicerVirtualReality/tree/slicervr-vtkrenderingvr-build

and this one if needed to successfully build:

* https://github.com/cpinter/SlicerVirtualReality/commits/gui-widgets-module

**Comment by jcfr** [comment]
Closing. This is superseded by https://github.com/KitwareMedical/SlicerVirtualReality/pull/90

**Pull request closed without merging**
