### PR TITLE
ENH: Generate convenience batch file on windows to start Slicer with …

### PR DESCRIPTION
**Pull request by cpinter**
…paths

Related to https://github.com/KitwareMedical/SlicerVirtualReality/issues/2

### CODE REVIEW

**Comment by cpinter** [comment]
I took a deeper look into the build, and the deployed dlls from the two dependency libraries seem alright after all. I added a convenience batch file though that makes it easier for windows developers to start Slicer with the necessary additional paths so that the module dlls can be loaded properly.

**Comment by jcfr** [comment]
This should work:

```
#-----------------------------------------------------------------------------
# Configure launcher for starting Slicer and ensure  the extension and its dependencies are loaded
find_package(CTKAppLauncher REQUIRED)
ctkAppLauncherConfigureForExecutable(
  APPLICATION_NAME SlicerWith${EXTENSION_NAME}
  APPLICATION_EXECUTABLE ${Slicer_DIR}/${Slicer_MAIN_PROJECT_APPLICATION_NAME}${CMAKE_EXECUTABLE_SUFFIX}
  APPLICATION_DEFAULT_ARGUMENTS "--launcher-additional-settings ${CMAKE_CURRENT_BINARY_DIR}/AdditionalLauncherSettings.ini"
  DESTINATION_DIR ${CMAKE_CURRENT_BINARY_DIR}
  )
```

I suggest you add it [here](https://github.com/Slicer/Slicer/blob/6e3daf5399dd355a4b80c1a39ad554fd12fea8fe/CMake/SlicerExtensionCPack.cmake#L217)

**Comment by jcfr** [comment]
I am also wondering, it `Slicer-with-${EXTENSION_NAME}` would be better

**Comment by lassoan** [comment]
I think SlicerWith${EXTENSION_NAME} is more consistent with existing file names. I don't remember seeing Slicer-with-${EXTENSION_NAME} style naming convention anywhere.

**Comment by cpinter** [comment]
I agree with Andras, the first launcher name seems more familiar.

Thanks for the updated code, it almost works. When starting the generated executable, I get this error:
error: Application does NOT exists [C:/d/_Extensions/SlicerVirtualReality_R/inner-build/../../../S4R/Slicer-build/Release/Slicer.exe]
Which is strange, because the APPLICATION_EXECUTABLE variable is set properly, and it is assembled to be C:/d/S4R/Slicer-build/Slicer.exe. I'm not sure where the 'Release' folder comes from.

**Comment by jcfr** [comment]
Try this:

```
#-----------------------------------------------------------------------------
# Configure launcher for starting Slicer and ensure the extension and its dependencies are loaded
# -------------------------------------------------------------------------
find_package(CTKAppLauncher REQUIRED)
# Workaround issue https://github.com/commontk/AppLauncher/issues/105
set(executable_dir "${Slicer_DIR}")
if(DEFINED CMAKE_CONFIGURATION_TYPES)
  set(executable_dir "${executable_dir}/..")
endif()
ctkAppLauncherConfigureForExecutable(
  APPLICATION_NAME SlicerWith${EXTENSION_NAME}
  APPLICATION_EXECUTABLE ${executable_dir}/${Slicer_MAIN_PROJECT_APPLICATION_NAME}${CMAKE_EXECUTABLE_SUFFIX}
  APPLICATION_DEFAULT_ARGUMENTS "--launcher-additional-settings ${CMAKE_CURRENT_BINARY_DIR}/AdditionalLauncherSettings.ini"
  DESTINATION_DIR ${CMAKE_CURRENT_BINARY_DIR}
)
```

If that works, I will commit adding you as co-author.

**Comment by cpinter** [comment]
I'm getting the very same error message. My hunch is that APPLICATION_EXECUTABLE is not actually used, and instead this variable is used from SlicerWithSlicerVirtualRealityLauncherSettings.ini:
path=<APPLAUNCHER_DIR>/../../../S4R/Release/Slicer.exe

PS: Please don't edit my comments. Your edit broke it and I had to edit it again to make everything show up what I typed.

**Comment by jcfr** [comment]
That issue should be fixed by https://github.com/commontk/AppLauncher/pull/106

You can test by replacing the content of `C:/d/S4R/CTKAPPLAUNCHER/CMake/ctkAppLauncher.cmake` by the one in the PR.

**Comment by cpinter** [comment]
Excellent, thanks! I'll try it now.

**Comment by cpinter** [comment]
Awesome, it works! Thank you very much! It will be much easier to use superbuild extensions for development with this.

**Comment by cpinter** [comment]
Do you want me to commit the Slicer change after the CTKAppLauncher PR is merged?

**Comment by jcfr** [comment]
> Do you want me to commit the Slicer change after the CTKAppLauncher PR is merged?

I will take care of it after I update `External_CTKAPPLAUNCHER ... `

**Comment by cpinter** [comment]
@jcfr Do you have any news on this? I think now that we basically have the code it should be integrated soon before we lose sight of this. Can I help?

**Comment by jcfr** [comment]
Since I didn't have a chance to fix the compilation of Qt5 statically on windows , it means I didn't update the, and it then also mean I didn't integrate this change.

Considering integrating this change is independent, here is a PR integrating it. See https://github.com/Slicer/Slicer/pull/1008 If that looks good, I will integrate.

> Can I help?

Help to build Qt5 statically on windows would be stellar.

**Comment by cpinter** [comment]
> Help to build Qt5 statically on windows would be stellar.

I'll give it a go.

**Comment by cpinter** [comment]
For the record: https://discourse.slicer.org/t/static-build-of-qt5-to-update-the-application-launcher-and-support-interactive-process

**Pull request closed without merging**
