### PR TITLE
Reworked module GUI and structure

### PR DESCRIPTION
**Pull request by lassoan**
- Added toolbar to enable/disable VR using a single click, without going to Virtual Reality module.
- Added GUI options to tune lighting settings (switch between 2/4 lights, enable/disable two-sided lighting).
- Added saving/restoring view state and properties to scene.
- Moved logic to logic class to allow configuring VR from other modules.
- Moved VR widget creation to module class to allow using VR without creating module widget.
- Made view widget creation inexpensive by not creating OpenVR renderer until hardware connection is requested (by setting view node Visibility to true).

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks Andras.

I just tried it and it works nicely.

That said, there are few issues:

* After loading the plugin, I can not click on the file menu. I can only use `ALT-F` or equivalent shortcut to access it

* There are some memory leaks on shutdown

**Comment by lassoan** [comment]
> After loading the plugin, I can not click on the file menu. I can only use ALT-F or equivalent shortcut to access it

fixed

> There are some memory leaks on shutdown

I could not reproduce this.

**Comment by lassoan** [comment]
@jcfr It would be great if this could be integrated before the nightly build starts. Matt Jolley would like to start using it as soon as possible. Thank you!

It could be also help if you could give me write access to the repository. Committing trivial fixes or documentation updates could be simpler to do directly rather than going through pull requests.

**Comment by jcfr** [comment]
Nice. Much better :smile:

**Comment by lassoan** [comment]
Perfect, thank you!

**Pull request merged**
