### PR TITLE
resolves #64 pass python library (for FindPackage(Python)) if VTK_PYT…

### LINKED ISSUE #64: PYTHON_LIBRARY is not passed to vtkRenderingOpenVR
Python lib location is not passed to project, and configure fails.

### PR DESCRIPTION
**Pull request by adamrankin**
…HON_WRAP is requested

### CODE REVIEW

**Comment by lassoan** [comment]
For me, PYTHON_LIBRARY is already defiend in ...\SlicerVirtualReality-win64rel\VTKRenderingOpenVR-build\CMakeCache.txt.

What is the problem that adding PYTHON_LIBRARY (again?) solves? How can I reproduce it?

**Comment by adamrankin** [comment]
When I do a clean build it can't find PythonLibs

**Comment by jcfr** [comment]
To clarify, this works:
* build Slicer
* build SlicerVirtualReality (clean build)

But this doesn't:

* build Slicer
* build SlicerVirtualReality (clean build)
* delete SlicerVirtualReality
* build SlicerVirtualReality (clean build) <--- FAIL

**Comment by lassoan** [comment]
It is OK to apply a quick workaround here, but could this be fixed in extension build macros in Slicer core?

**Comment by adamrankin** [comment]
@jcfr you're absolutely right, that's the case

totally up to you guys if you want to accept the workaround, or wait for a core fix. it's easy for me to just fix up the CMake each time.

**Comment by jcfr** [comment]
On windows, it turns out the following systematically happen during the configuration of the vtkRenderingOpenVR module... (even after I remove the vtkRenderingOpenVR* files created in `D:\path\to\Slicer-superbuild\VTK-build\lib/cmake ...`)
```
[...]
  loading initial cache file D:/D/P/S-0-E-b/SlicerVirtualReality-build/VTKRenderingOpenVR-prefix/tmp/VTKRenderingOpenVR-cache-Release.cmake
[...]
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonLibs: C:/Python36-x64/libs/python36.lib
[...]
  -- Found OpenGL: opengl32
  -- Configuring done
```

And on linux, I observed the following:

```
[...]
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so  
-- Performing Test VTK_UNDEFINED_SYMBOLS_ALLOWED - Success
-- Found OpenVR: /home/jcfr/Projects/SlicerVirtualReality-build/OpenVR/headers  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
[...]
```

This started to happen after I integrated support for building python wrapper library for externally built VTK module. 

@adamrankin I will review and integrate your fix.

@lassoan A proper fix would be to ensure PYTHON_* variable are added to the VTKConfig file so that modules re-use them. That said, considering that the VTK build system has completely been re-written in VTK master ... it is not worth spending time doing so (at least not until we use the newer build system for Slicer/VTK)

**Pull request merged**
